#!/sbin/openrc-run
# Copyright 2016-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="LLS Exporter"
description="LLS Exporter for rs485/rs232 lls fuel level sensors"
pidfile=${pidfile:-"/run/${SVCNAME}.pid"}
command_user=${command_user:-nobody:dialout}

command="/usr/bin/lls_exporter"
command_background=true
retry="${retry:-TERM/20/KILL/5}"

depend() {
	need net
	after net
}
