#!/sbin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

description="Prometheus Bot"

pidfile="/run/${SVCNAME}.pid"
command=/usr/bin/prometheus-bot
command_args="${PROMETHEUS_BOT_ARGS}"
command_background="true"

start_stop_daemon_args="-u ${PROMETHEUS_BOT_USER} -1 ${PROMETHEUS_BOT_LOG_FILE} -2 ${PROMETHEUS_BOT_LOG_FILE}"

depend() {
	need net
}
