Index: Makefile
===================================================================
diff --git a/trunk/xupnpd/src/Makefile b/trunk/xupnpd/src/Makefile
--- a/Makefile	(revision 368)
+++ b/Makefile	(working copy)
@@ -1,8 +1,8 @@
-LUA     = lua-5.1.4
-#LUA     = lua-5.2.0
+CC ?= gcc
+CXX ?= g++
+
 STATIC  = false
 
-CFLAGS  = -fno-exceptions -fno-rtti -O2 -I$(LUA) -L$(LUA)
 SRC     = main.cpp soap.cpp mem.cpp mcast.cpp luaxlib.cpp luaxcore.cpp luajson.cpp luajson_parser.cpp
 STAGING_DIR = /u01//home/shocker/staff/openwrt/staging_dir
 LUAMYCFLAGS = -DLUA_USE_LINUX
@@ -16,10 +16,8 @@ LUAMYCFLAGS+=-static
 endif
 
 x86:
-	$(MAKE) -C $(LUA) CC=$(CC) a
 	$(CC) -O2 -c -o md5.o md5c.c
-	$(CC) $(CFLAGS) -DWITH_LIBUUID -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -o xupnpd $(SRC) md5.o -llua -ldl -lm -luuid
-	strip xupnpd
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) -fno-exceptions -fno-rtti -DWITH_LIBUUID -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -o xupnpd $(SRC) md5.o -llua -ldl -lm -luuid
 
 # Cygwin
 x86win:
