#!/sbin/openrc-run
# Copyright 2016-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Mobell proxy, companion for mobell android app and mobotix cameras"
pidfile=${pidfile:-"/run/${SVCNAME}.pid"}
command_user=${command_user:-mobell-proxy:mobell-proxy}

command="/usr/bin/mobell-proxy"
command_background=true
retry="${retry:-TERM/20/KILL/5}"

depend() {
	need net
	after net
}
