#!/sbin/openrc-run
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: $

export JAVA_HOME=${JAVA_HOME:-$(java-config -o)}

export CASSANDRA_HOME=${CASSANDRA_HOME:-"/opt/cassandra"}
export CASSANDRA_CONF=${CASSANDRA_CONF:-"/etc/cassandra"}
export CASSANDRA_USER=${CASSANDRA_USER:-"cassandra"}
export CASSANDRA_STORAGE=${CASSANDRA_STORAGE:-"/var/lib/cassandra"}
export CASSANDRA_PID=${CASSANDRA_PID:-"/var/run/cassandra.pid"}
export CASSANDRA_LOG_DIR=${CASSANDRA_LOG_DIR:-"/var/log/cassandra"}
export CASSANDRA_LOG="${CASSANDRA_LOG_DIR}/output.log"

export JVM_OPTS="${JVM_OPTS} -XX:+IgnoreUnrecognizedVMOptions -Djna.tmpdir=/tmp/cassandra-jna"
[[ "${JVM_OPTS_SECURITY}" != "no" ]] && export JVM_OPTS="${JVM_OPTS} -Djava.security.manager=allow"

modules=( java.io sun.nio.ch java.util java.util.concurrent java.util.concurrent.atomic java.nio java.lang java.math )
for module in "${modules[@]}"
do
	export JVM_OPTS="${JVM_OPTS} --add-opens java.base/${module}=ALL-UNNAMED"
done

FD_LIMIT=${FD_LIMIT:-1000000}

depend() {
	use net
	provide cassandra
}

start()	{
	ebegin "Starting Cassandra"

	ulimit -l unlimited
	ulimit -n "$FD_LIMIT"

	start-stop-daemon -S -b -m -p ${CASSANDRA_PID} -u ${CASSANDRA_USER} -1 ${CASSANDRA_LOG} -2 ${CASSANDRA_LOG} \
		--exec "${CASSANDRA_HOME}"/bin/cassandra -- -f

	eend $?
}

stop ()	{
	ebegin "Stopping Cassandra"

	start-stop-daemon -K -p ${CASSANDRA_PID} --progress --retry "SIGHUP/30 SIGTERM/15 SIGKILL/15"

	eend $?
}

