#!/sbin/openrc-run
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: $

JAVA=${JAVA:-$(java-config -J)}

CASSANDRA_HOME=${CASSANDRA_HOME:-"/opt/cassandra"}
CASSANDRA_CONF=${CASSANDRA_CONF:-"/etc/cassandra"}
CASSANDRA_USER=${CASSANDRA_USER:-"cassandra"}
CASSANDRA_STORAGE=${CASSANDRA_STORAGE:-"/var/lib/cassandra"}
CASSANDRA_PID=${CASSANDRA_PID:-"/var/run/cassandra.pid"}
CASSANDRA_LOGS=${CASSANDRA_LOGS:-"/var/log/cassandra"}
CASSANDRA_LOG="${CASSANDRA_LOGS}/output.log"

FD_LIMIT=${FD_LIMIT:-1000000}

depend() {
	use net
	provide cassandra
}

start()	{
	ebegin "Starting Cassandra"

	. ${CASSANDRA_CONF}/cassandra-env.sh

	ulimit -l unlimited
	ulimit -n "$FD_LIMIT"

	start-stop-daemon -S -b -m -p ${CASSANDRA_PID} -u ${CASSANDRA_USER} -1 ${CASSANDRA_LOG} -2 ${CASSANDRA_LOG} \
		--exec "${JAVA}" -- -cp "`classpath`" -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=${CASSANDRA_LOGS} -Dcassandra.storagedir=${CASSANDRA_STORAGE} $JVM_OPTS org.apache.cassandra.service.CassandraDaemon

	eend $?
}

stop ()	{
	ebegin "Stopping Cassandra"

	. ${CASSANDRA_CONF}/cassandra-env.sh

	start-stop-daemon -K -p ${CASSANDRA_PID} --progress --retry "SIGHUP/30 SIGTERM/15 SIGKILL/15"

	eend $?
}

classpath()
{
    cp="$EXTRA_CLASSPATH"
    for j in ${CASSANDRA_HOME}/lib/*.jar; do
        [ "x$cp" = "x" ] && cp=$j || cp=$cp:$j
    done
    for j in ${CASSANDRA_HOME}/*.jar; do
        [ "x$cp" = "x" ] && cp=$j || cp=$cp:$j
    done

    # use JNA if installed in standard location
    [ -r /usr/share/jna/lib/jna.jar ] && cp="$cp:/usr/share/jna/lib/jna.jar"

    # Include the conf directory for purposes of log4j-server.properties, and
    # commons-daemon in support of the daemonization class.
    printf "$cp:$CASSANDRA_CONF"
}

